#!/bin/bash
export PATH=$PATH:/home/matt/lib/
export PATH=$PATH:~/Install/Programs/mendeley/bin/
export PATH=$PATH:~/Libraries/eigen-dev/unsupported/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/Eigen
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/
# this line is currently incorrect
export MITSCHEME_LIBRARY_PATH=/home/matt/lib/mit-scheme-x86-64


# add the pkg_path
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:~/Libraries/allegro/lib/pkgconfig/
export path=$PATH:~/Libraries/allegro/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/Libraries/allegro/lib/
export C_INCLUDE_PATH=$C_INCLUDE_PATH:~/Libraries/allegro/include/
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:~/Libraries/allegro/include
export LIBRARY_PATH=$LIBRARY_PATH:~/Libraries/allegro/lib

# install
export PATH=$PATH:~/Code/Graphics/OpenGL/Premake/
# export PATH=$PATH:~/Install/mit-scheme/bin/
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/Install/mit-scheme/lib/
export MPIRUN="mpirun -mca btl ^sm"

